# docker-compose.yml - ФИНАЛЬНАЯ ВЕРСЯ

services:
  db:
    image: postgres:15-alpine
    container_name: bonafide_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - bonafide_network

  backend:
    build: ./backend
    container_name: bonafide_backend
    volumes:
      # --- ИЗМЕНЕНИЕ 1 ---
      # Теперь мы используем именованные тома
      - staticfiles_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - bonafide_network

  nginx:
    build: ./frontend
    container_name: bonafide_nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      # --- ИЗМЕНЕНИЕ 2 ---
      # Подключаем ТЕ ЖЕ САМЫЕ именованные тома для чтения
      - staticfiles_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - bonafide_network

# --- ИЗМЕНЕНИЕ 3 ---
# Переименовываем тома для ясности
volumes:
  postgres_data:
  staticfiles_volume:
  media_volume:

networks:
  bonafide_network:
    driver: bridge